### ISSUE TITLE
Error Uncaught (in promise) when refetching

### ISSUE THREAD

**Issue by tetiogit** [apollographql/graphql-tutorial#5]
Following part3 of tutorial I was not able to refetch properly after hit enter, this is the error on the console

```
apollo.umd.js:1804 Uncaught (in promise) Error: Network error: Cannot read property 'kind' of undefined
    at new ApolloError (apollo.umd.js:1804)
    at apollo.umd.js:2473
ApolloError	@	apollo.umd.js:1804
(anonymous)	@	apollo.umd.js:2473
```
don't have any idea of where is coming from

**Comment by hjohns** [comment]
Don't know if it's related, but I had a similar problem with uncaught promises that was fixed by updating react-scripts in the package.json from 0.9.3 to 0.9.5:
```
"devDependencies": {
    "react-scripts": "^0.9.5"
  }
```
https://github.com/facebookincubator/create-react-app/issues/1776

**Comment by jdhines** [comment]
I'm getting the same exact issue as @tetiogit. I updated `react-scripts` to 0.9.5, restarted client and server, and still getting this issue. The new item is still added, and the polling takes place and pulls the new value back, but the input doesn't clear out, and the query doesn't run immediately.

**Comment by hammannja** [comment]
I have the same issue described above. Not sure whether it matters or not, but I am using a Windows PC, so some of the optional dependencies (like fsevents) do not load.

**Comment by helfer** [comment]
Hm, strange, I haven't seen those errors. Could one of you create a github repo with your solution so I can try to run it? As @hammannja pointed out, it might have something to do with the platform.

**Comment by jpabbuehl** [comment]
same for me, I am using Ubuntu 16.10
the "offending" line is also the same for me: refetchQueries: [{ query: channelsListQuery}]

**Comment by kul1010** [comment]
I have seen same error in chrome browser's console.
apollo.umd.js:1804 Uncaught (in promise) Error: Network error: Cannot read property 'kind' of undefined
    at new ApolloError (apollo.umd.js:1804)
    at apollo.umd.js:2473
    at <anonymous>

**Comment by kul1010** [comment]
first clone branch
$git clone https://github.com/apollographql/graphql-tutorial.git
1. take checkout with t3-end branch
   $ git checkout t3-end
2. after this 
   $ git fetch
3. cd client 
4. npm i --save
5. npm start
and other git bash or command prompt
1. cd server
2. npm i
3. npm start

issue resolved. Thanks.

**Comment by mikeshinoda** [comment]
I think I have found the solution. We need to export the channelsListQuery from ChannelsListWithData.js to make it useful in AddChannel.js

**Comment by davidctj** [comment]
@mikeshinoda  is correct, write channelsListQuery in `ChannelsListWithData.js` as below
```
export const channelsListQuery = gql`
  query ChannelsListQuery {
    channels {
      id
      name
    }
  }
`;
```

**Comment by adam-ainsworth** [comment]
Thanks very much, @davidctj - I spent an age trying to debug this on my own. The code really needs to be updated!

**Comment by helfer** [comment]
I don't know if it wasn't in the tutorial earlier, but it's definitely in there now, and it's also in the t3-end branch, so I'm going to close the issue. Thanks for everyone who pointed it out and helped debug!

**Comment by webmobiles** [comment]
tutorial step 3 have this error, i solved adding export to 'const channelsListQuery" in this block in ChannelsListWIthData.js

export const channelsListQuery = gql`
  query ChannelsListQuery {
    channels {
      id
      name
    }
  }
`;

export default graphql(channelsListQuery)(ChannelsList);
